# Generated by Django 4.1.5 on 2023-01-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setmeup", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lichbaocao",
            options={"ordering": ["-pk"]},
        ),
        migrations.AddField(
            model_name="lichbaocao",
            name="noidung",
            field=models.TextField(null=True),
        ),
    ]
