# Generated by Django 4.1.5 on 2023-01-16 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("setmeup", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lichbaocao",
            name="ref",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="setmeup.lichdinhky",
            ),
        ),
        migrations.AlterField(
            model_name="lichbaocao",
            name="kind",
            field=models.SmallIntegerField(
                choices=[(0, "Khẩn"), (1, "Đột xuất"), (2, "Định kỳ")]
            ),
        ),
        migrations.DeleteModel(
            name="LoaiLich",
        ),
    ]
