# Generated by Django 4.1.5 on 2023-01-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setmeup", "0002_lichbaocao_ref_alter_lichbaocao_kind_delete_loailich"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lichbaocao",
            name="ref",
        ),
        migrations.AddField(
            model_name="lichbaocao",
            name="dinhky",
            field=models.SmallIntegerField(
                choices=[
                    (0, "Tháng"),
                    (1, "Quý"),
                    (2, "Năm"),
                    (3, "6 tháng"),
                    (4, "9 tháng"),
                ],
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="LichDinhKy",
        ),
    ]
