# Generated by Django 4.1.5 on 2023-01-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setmeup", "0003_remove_lichbaocao_ref_lichbaocao_dinhky_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lichbaocao",
            name="dinhky",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (0, "Tháng"),
                    (1, "Quý"),
                    (2, "Năm"),
                    (3, "6 tháng"),
                    (4, "9 tháng"),
                ],
                null=True,
            ),
        ),
    ]
