# Generated by Django 4.1.5 on 2023-01-16 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-pk"]},
        ),
    ]
