# Generated by Django 4.1.5 on 2023-01-16 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("setmeup", "0001_initial"),
        ("baocao", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="baocao",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="baocao",
            name="nguoi_duyet",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nguoi_duyet",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="baocao",
            name="nguoi_ky",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nguoi_ky",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="baocao",
            name="nguoi_soan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nguoi_soan",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="baocao",
            name="nof",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="setmeup.lichbaocao",
            ),
        ),
        migrations.AddField(
            model_name="baocao",
            name="noinhan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="setmeup.noinhan",
            ),
        ),
        migrations.AddField(
            model_name="baocao",
            name="phongban",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="setmeup.phongban",
            ),
        ),
    ]
