# Generated by Django 4.1.5 on 2023-01-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baocao", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThongKe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.SmallIntegerField(
                        choices=[(1, "Tháng"), (2, "Quý"), (3, "Năm")]
                    ),
                ),
                ("val", models.SmallIntegerField()),
                ("year", models.SmallIntegerField()),
                ("baocao", models.ManyToManyField(to="baocao.baocao")),
            ],
        ),
    ]
