# Generated by Django 4.1.5 on 2023-01-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baocao", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediafile",
            name="filename",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="filetype",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
