# Generated by Django 4.1.5 on 2023-01-16 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baocao", "0003_mediafile_filename_mediafile_filetype"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="baocao",
            options={"ordering": ["-pk"]},
        ),
    ]
